name: Test Fail with Secret Policy

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-fail-secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use secrets (should be blocked on non-default branch)
        run: |
          echo "Secret value: ${{ secrets.GITHUB_TOKEN }}"
          echo "API Key: ${{ secrets.API_KEY }}"
          echo "This workflow uses secrets and should be blocked on non-default branch"

      - name: Use toJSON secrets pattern  
        run: |
          echo "All secrets: ${{ toJSON(secrets) }}"
          echo "This pattern should also trigger the secret policy"

      - name: Display results
        run: |
          echo "Workflow completed successfully"
          echo "This is a fail scenario for secret policy enforcement"
          echo "NOTE: This workflow should be tested from a non-default branch"
          echo "with different content than the default branch version"