name: Test Fail with Runs-On Policy

on:
  workflow_dispatch:

jobs:
  test-fail-runs-on:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test on disallowed runner
        run: |
          echo "Running on windows-latest (should be blocked)"
          echo "This workflow uses disallowed runner labels"

      - name: Display results
        run: |
          echo "Workflow completed successfully"
          echo "This is a fail scenario for runs-on policy enforcement"

  test-fail-self-hosted:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test on self-hosted runner
        run: |
          echo "Running on self-hosted (should be blocked)"
          echo "This workflow uses self-hosted runner labels"