name: Test Fail with Compromised Action

on:
  workflow_dispatch:

jobs:
  test-fail:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use compromised action (should be blocked)
        uses: step-security/dummy-compromised-action@v1

      - name: Display results
        run: |
          echo "Workflow completed successfully"
          echo "This is a fail scenario for workflow run policies"
